spring:
  application:
    name: vmc

  datasource:
    url: jdbc:postgresql://localhost:5432/vmc
    username: muku
    password: root

  jpa:
    properties:
      hibernate:
        default_schema: vmc
        show_sql: true
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
